### ISSUE TITLE
Make codeclimate working

### ISSUE THREAD

**Issue by petrblaho** [zonkylla/zonkylla#114]
After move to zonkylla org codeclimate is not set up.

Make codeclimate working again.
Correct codeclimate badge in README.

**Comment by celestian** [comment]
OK, at the moment, it is not possible to link this zonkylla repo with CodeClimate because I have linked my personal one (celestian/zonkylla).
So, I deleted my CodeClimate account and I will way couple of days. (New account immediately after deletion is not working -- I've seen my old data.)

**Comment by celestian** [comment]
I created new account on CodeClimate, it works not. Now we need to change the link in README to proper one.
